/**
 * Block Definitions for Italian Insurance Trace Files
 *
 * Defines the structure of all supported block types:
 * - System blocks: CNT, SCH, PRT, PAX, RIS, DOC, RIN, SFO, AGE, COA, CVP, COI, PCE, LPS, PCB
 * - Anagrafica blocks: CPERSONA, CNATANTE, CIMPRESA, CFABBRICATO, CUBICAZIONE, CATTIVITA,
 *                      CVEICOLO, CENTITASTRINGA, CGRUPPOANAG, CAEROMOBILE, CUSISPECIALI, CANIMALE
 * - Relation blocks: CRELAZIONERR, CRELAZIONEGR, CRELAZIONECR
 * - Variant blocks: CPERSGRUP, CPERSAERO, CUBICAZGRUP, CUBICAZAERO, CIMPRESAGRUP, CRELAZRRAERO, CRELAZRRGRUP
 *
 * Line structure: [0-109: Header][109-200: Version][200-230: Block name][230+: Block data]
 *
 * Each block definition specifies:
 * - name: Field name
 * - pos: Position within block data (relative to position 230 in the line)
 * - len: Field length in characters
 */

export const BLOCK_DEFINITIONS = {
    'CNT': [
        { name: 'COD_COMP', pos: 0, len: 4 },
        { name: 'NUM_CONTRATTO', pos: 4, len: 14 },
        { name: 'PRG_CONTRATTO', pos: 18, len: 8 },
        { name: 'DAT_FINE_VAL', pos: 26, len: 10 },
        { name: 'TIP_PORTAF', pos: 36, len: 1 },
        { name: 'COD_STATO_PTF', pos: 37, len: 1 },
        { name: 'TIP_DOCUMENTO_MOD', pos: 38, len: 2 },
        { name: 'NUM_DOCUMENTO_MOD', pos: 40, len: 14 },
        { name: 'DAT_DECORRENZA', pos: 54, len: 10 },
        { name: 'DAT_SCADENZA', pos: 64, len: 10 },
        { name: 'NUM_DURATA', pos: 74, len: 8 },
        { name: 'COD_FRAZIONAMENTO', pos: 82, len: 1 },
        { name: 'NUM_AGENZIA', pos: 83, len: 8 },
        { name: 'COD_ESENZIONE', pos: 91, len: 1 },
        { name: 'COD_ANNULL_CON', pos: 92, len: 3 },
        { name: 'DAT_ANNULL_CON', pos: 95, len: 10 },
        { name: 'COD_ANNULL_SUB', pos: 105, len: 3 },
        { name: 'COD_ANNULL_USER', pos: 108, len: 8 },
        { name: 'DAT_ANNULL_REG', pos: 116, len: 10 },
        { name: 'KEY_AUTOR', pos: 126, len: 10 },
        { name: 'COD_COASS', pos: 136, len: 1 },
        { name: 'COD_VINCOLO', pos: 137, len: 1 },
        { name: 'COD_RINNOVO', pos: 138, len: 1 },
        { name: 'TIP_CONVENZ', pos: 139, len: 1 },
        { name: 'COD_CONVERS', pos: 140, len: 2 },
        { name: 'COD_VALUTA', pos: 142, len: 4 },
        { name: 'ORA_DEC_IMMEDIATA', pos: 146, len: 5 },
        { name: 'COD_PER_RESCIND', pos: 151, len: 2 },
        { name: 'DAT_RESCINDIB', pos: 153, len: 10 },
        { name: 'TIP_STRUTTURA', pos: 163, len: 2 },
        { name: 'COD_DIR_CONTI', pos: 165, len: 2 },
        { name: 'DAT_RIF_TABELLE', pos: 167, len: 10 },
        { name: 'COD_LINGUA', pos: 177, len: 2 },
        { name: 'COD_FRAZ_PROROG', pos: 179, len: 1 },
        { name: 'COD_CONGUAGLIO', pos: 180, len: 1 },
        { name: 'DAT_APPLIC_AR', pos: 181, len: 10 },
        { name: 'TIP_RISK', pos: 191, len: 1 },
        { name: 'DAT_RIATTIVAZ', pos: 192, len: 10 },
        { name: 'COD_RIASS', pos: 202, len: 4 },
        { name: 'COD_INDICIZZ', pos: 206, len: 1 },
        { name: 'COD_BLOK_INDIC', pos: 207, len: 1 },
        { name: 'COD_TAB_INDIC', pos: 208, len: 2 },
        { name: 'COD_GEST_PROVV', pos: 210, len: 1 },
        { name: 'COD_RIPRESA', pos: 211, len: 2 },
        { name: 'COD_PRODOTTO_GRV', pos: 213, len: 6 },
        { name: 'COD_PROD_SUPER', pos: 219, len: 4 },
        { name: 'COD_EDIZ_STAMPATO', pos: 223, len: 4 },
        { name: 'COD_RAMOPOL', pos: 227, len: 4 },
        { name: 'COD_CATEGORIA', pos: 231, len: 4 },
        { name: 'COD_STORNO_SIDA', pos: 235, len: 3 },
        { name: 'PER_NS_QUOTA', pos: 238, len: 7 },
        { name: 'FLG_CONDELEGA', pos: 245, len: 1 },
        { name: 'COD_ACQUISITORE', pos: 246, len: 7 },
        { name: 'DAT_CONTAB_PROT', pos: 253, len: 10 },
        { name: 'DAT_CONTAB_ANN', pos: 263, len: 10 },
        { name: 'DAT_INIZ_VAL', pos: 273, len: 10 },
        { name: 'COD_USER_INS', pos: 283, len: 8 },
        { name: 'TMS_INS', pos: 291, len: 28 },
        { name: 'COD_USER_MOD', pos: 317, len: 8 },
        { name: 'TMS_MOD', pos: 325, len: 28 },
        { name: 'COD_ADEGUAMENTO', pos: 351, len: 1 },
        { name: 'COD_COMP_C', pos: 352, len: 4 },
        { name: 'FLG_DIGITALE', pos: 356, len: 1 },
        { name: 'COD_PROPOSTA', pos: 357, len: 1 },
        { name: 'COD_MODULARE', pos: 358, len: 1 },
        { name: 'COD_ANTIMAFIA', pos: 359, len: 1 }
    ],
    'SCH': [
        { name: 'COD_COMP', pos: 0, len: 4 },
        { name: 'NUM_CONTRATTO', pos: 4, len: 14 },
        { name: 'PRG_CONTRATTO', pos: 18, len: 8 },
        { name: 'PRG_SCHEDA', pos: 26, len: 8 },
        { name: 'DAT_FINE_VAL', pos: 34, len: 10 },
        { name: 'COD_RAMO_ATOM', pos: 44, len: 5 },
        { name: 'DAT_DECORRENZA', pos: 49, len: 10 },
        { name: 'DAT_SCADENZA', pos: 59, len: 10 },
        { name: 'IMP_PREMIO', pos: 69, len: 16 },
        { name: 'COD_ANN_SKE', pos: 85, len: 2 },
        { name: 'DAT_ANN_SKE', pos: 87, len: 10 },
        { name: 'COD_ANNULL_USER', pos: 97, len: 8 },
        { name: 'DAT_ANNULL_REG', pos: 105, len: 10 },
        { name: 'TIP_DOCUMENTO_MOD', pos: 115, len: 2 },
        { name: 'NUM_DOCUMENTO_MOD', pos: 117, len: 14 },
        { name: 'COD_RICALCOLO', pos: 131, len: 1 },
        { name: 'TIP_RINNOVO_SCHEDA', pos: 132, len: 2 },
        { name: 'COD_CONTAB', pos: 134, len: 1 },
        { name: 'COD_RAMO_FORTE', pos: 135, len: 5 },
        { name: 'COD_RELAZIONE', pos: 140, len: 1 },
        { name: 'PRG_MADRE', pos: 141, len: 8 },
        { name: 'TIP_RISK_PROVV', pos: 149, len: 3 },
        { name: 'COD_VALUTA', pos: 152, len: 4 },
        { name: 'COD_CONVERS', pos: 156, len: 2 },
        { name: 'DAT_APPLIC_DC', pos: 158, len: 10 },
        { name: 'COD_DIR_CONTI', pos: 168, len: 2 },
        { name: 'COD_CONGUAGLIO', pos: 170, len: 1 },
        { name: 'COD_INDICIZZ', pos: 171, len: 1 },
        { name: 'COD_BLOK_INDIC', pos: 172, len: 1 },
        { name: 'COD_TAB_INDIC', pos: 173, len: 2 },
        { name: 'DAT_ULT_INDIC', pos: 175, len: 10 },
        { name: 'NUM_ISTAT', pos: 185, len: 5 },
        { name: 'PER_INCRE_ISTAT', pos: 190, len: 8 },
        { name: 'PER_INCRE_ETA', pos: 198, len: 8 },
        { name: 'COD_LANCIO_PVAG', pos: 206, len: 7 },
        { name: 'COD_RAMOGAR', pos: 213, len: 4 },
        { name: 'COD_CATEG_GAR', pos: 217, len: 4 },
        { name: 'DAT_INIZ_VAL', pos: 221, len: 10 },
        { name: 'COD_USER_INS', pos: 231, len: 8 },
        { name: 'TMS_INS', pos: 239, len: 28 },
        { name: 'COD_USER_MOD', pos: 265, len: 8 },
        { name: 'TMS_MOD', pos: 273, len: 28 },
        { name: 'COD_ADEGUAMENTO', pos: 299, len: 1 },
        { name: 'DAT_ADEGUAMENTO', pos: 300, len: 10 },
        { name: 'COD_LIVELLO_ADEG', pos: 310, len: 1 }
    ],
    'PRT': [
        { name: 'COD_COMP', pos: 0, len: 4 },
        { name: 'NUM_CONTRATTO', pos: 4, len: 14 },
        { name: 'PRG_CONTRATTO', pos: 18, len: 8 },
        { name: 'PRG_SCHEDA', pos: 26, len: 8 },
        { name: 'PRG_PARTITA', pos: 34, len: 6 },
        { name: 'DAT_FINE_VAL', pos: 40, len: 10 },
        { name: 'COD_RAMO_ATOM', pos: 50, len: 5 },
        { name: 'COD_GAR_LIV1', pos: 55, len: 3 },
        { name: 'COD_GAR_LIV2', pos: 58, len: 3 },
        { name: 'COD_GAR_LIV3', pos: 61, len: 3 },
        { name: 'COD_GAR_SUB', pos: 64, len: 1 },
        { name: 'COD_CLA_ID', pos: 65, len: 3 },
        { name: 'COD_CLA_SUB', pos: 68, len: 1 },
        { name: 'DAT_TARIFFA', pos: 69, len: 10 },
        { name: 'COD_TARIFFA', pos: 79, len: 3 },
        { name: 'DAT_INGRESSO_TAR', pos: 82, len: 10 },
        { name: 'IMP_PREMIO', pos: 92, len: 14 },
        { name: 'COD_VALUTA', pos: 106, len: 4 },
        { name: 'COD_TAR_PROVIN', pos: 110, len: 3 },
        { name: 'COD_TAR_ZONA', pos: 113, len: 3 },
        { name: 'IMP_PREMIO_TECNICO', pos: 116, len: 14 },
        { name: 'COD_FORZATURA', pos: 130, len: 1 },
        { name: 'DAT_INIZ_VAL', pos: 131, len: 10 },
        { name: 'COD_USER_INS', pos: 141, len: 8 },
        { name: 'TMS_INS', pos: 149, len: 28 },
        { name: 'COD_USER_MOD', pos: 175, len: 8 },
        { name: 'TMS_MOD', pos: 183, len: 28 }
    ],
    'PAX': [
        { name: 'COD_COMP', pos: 0, len: 4 },
        { name: 'NUM_CONTRATTO', pos: 4, len: 14 },
        { name: 'PRG_CONTRATTO', pos: 18, len: 8 },
        { name: 'PRG_SCHEDA', pos: 26, len: 8 },
        { name: 'PRG_PARTITA', pos: 34, len: 6 },
        { name: 'PRG_RCD_PARAM', pos: 40, len: 2 },
        { name: 'DAT_FINE_VAL', pos: 42, len: 10 },
        { name: 'COD_CLA_ID_01', pos: 52, len: 3 },
        { name: 'COD_CLA_SUB_01', pos: 55, len: 1 },
        { name: 'NUM_PVLS_01', pos: 56, len: 8 },
        { name: 'VAL_PARAMETRO_01', pos: 64, len: 14 },
        { name: 'COD_PRESTAZ_01', pos: 78, len: 2 },
        { name: 'COD_CLA_ID_02', pos: 80, len: 3 },
        { name: 'COD_CLA_SUB_02', pos: 83, len: 1 },
        { name: 'NUM_PVLS_02', pos: 84, len: 8 },
        { name: 'VAL_PARAMETRO_02', pos: 92, len: 14 },
        { name: 'COD_PRESTAZ_02', pos: 106, len: 2 },
        { name: 'COD_CLA_ID_03', pos: 108, len: 3 },
        { name: 'COD_CLA_SUB_03', pos: 111, len: 1 },
        { name: 'NUM_PVLS_03', pos: 112, len: 8 },
        { name: 'VAL_PARAMETRO_03', pos: 120, len: 14 },
        { name: 'COD_PRESTAZ_03', pos: 134, len: 2 },
        { name: 'COD_CLA_ID_04', pos: 136, len: 3 },
        { name: 'COD_CLA_SUB_04', pos: 139, len: 1 },
        { name: 'NUM_PVLS_04', pos: 140, len: 8 },
        { name: 'VAL_PARAMETRO_04', pos: 148, len: 14 },
        { name: 'COD_PRESTAZ_04', pos: 162, len: 2 },
        { name: 'COD_CLA_ID_05', pos: 164, len: 3 },
        { name: 'COD_CLA_SUB_05', pos: 167, len: 1 },
        { name: 'NUM_PVLS_05', pos: 168, len: 8 },
        { name: 'VAL_PARAMETRO_05', pos: 176, len: 14 },
        { name: 'COD_PRESTAZ_05', pos: 190, len: 2 },
        { name: 'COD_CLA_ID_06', pos: 192, len: 3 },
        { name: 'COD_CLA_SUB_06', pos: 195, len: 1 },
        { name: 'NUM_PVLS_06', pos: 196, len: 8 },
        { name: 'VAL_PARAMETRO_06', pos: 204, len: 14 },
        { name: 'COD_PRESTAZ_06', pos: 218, len: 2 },
        { name: 'COD_CLA_ID_07', pos: 220, len: 3 },
        { name: 'COD_CLA_SUB_07', pos: 223, len: 1 },
        { name: 'NUM_PVLS_07', pos: 224, len: 8 },
        { name: 'VAL_PARAMETRO_07', pos: 232, len: 14 },
        { name: 'COD_PRESTAZ_07', pos: 246, len: 2 },
        { name: 'COD_CLA_ID_08', pos: 248, len: 3 },
        { name: 'COD_CLA_SUB_08', pos: 251, len: 1 },
        { name: 'NUM_PVLS_08', pos: 252, len: 8 },
        { name: 'VAL_PARAMETRO_08', pos: 260, len: 14 },
        { name: 'COD_PRESTAZ_08', pos: 274, len: 2 },
        { name: 'COD_CLA_ID_09', pos: 276, len: 3 },
        { name: 'COD_CLA_SUB_09', pos: 279, len: 1 },
        { name: 'NUM_PVLS_09', pos: 280, len: 8 },
        { name: 'VAL_PARAMETRO_09', pos: 288, len: 14 },
        { name: 'COD_PRESTAZ_09', pos: 302, len: 2 },
        { name: 'COD_CLA_ID_10', pos: 304, len: 3 },
        { name: 'COD_CLA_SUB_10', pos: 307, len: 1 },
        { name: 'NUM_PVLS_10', pos: 308, len: 8 },
        { name: 'VAL_PARAMETRO_10', pos: 316, len: 14 },
        { name: 'COD_PRESTAZ_10', pos: 330, len: 2 },
        { name: 'DAT_INIZ_VAL', pos: 332, len: 10 },
        { name: 'COD_USER_INS', pos: 342, len: 8 },
        { name: 'TMS_INS', pos: 350, len: 28 },
        { name: 'COD_INDICIZZ_01', pos: 376, len: 1 },
        { name: 'COD_INDICIZZ_02', pos: 377, len: 1 },
        { name: 'COD_INDICIZZ_03', pos: 378, len: 1 },
        { name: 'COD_INDICIZZ_04', pos: 379, len: 1 },
        { name: 'COD_INDICIZZ_05', pos: 380, len: 1 },
        { name: 'COD_INDICIZZ_06', pos: 381, len: 1 },
        { name: 'COD_INDICIZZ_07', pos: 382, len: 1 },
        { name: 'COD_INDICIZZ_08', pos: 383, len: 1 },
        { name: 'COD_INDICIZZ_09', pos: 384, len: 1 },
        { name: 'COD_INDICIZZ_10', pos: 385, len: 1 }
    ],
    'RIS': [
        { name: 'COD_COMP', pos: 0, len: 4 },
        { name: 'NUM_CONTRATTO', pos: 4, len: 14 },
        { name: 'PRG_CONTRATTO', pos: 18, len: 8 },
        { name: 'PRG_SCHEDA', pos: 26, len: 8 },
        { name: 'PRG_PARTITA', pos: 34, len: 6 },
        { name: 'NUM_QUESTION', pos: 40, len: 8 },
        { name: 'NUM_DOMANDA', pos: 48, len: 6 },
        { name: 'PRG_RISPOSTA', pos: 54, len: 4 },
        { name: 'NUM_RIGA_RISP', pos: 58, len: 4 },
        { name: 'DAT_FINE_VAL', pos: 62, len: 10 },
        { name: 'TIP_RISPOSTA', pos: 72, len: 1 },
        { name: 'TIP_DATA', pos: 73, len: 1 },
        { name: 'VAL_RISPOSTA', pos: 74, len: 14 },
        { name: 'TXT_RISPOSTA', pos: 88, len: 70 },
        { name: 'NUM_LISTA', pos: 158, len: 8 },
        { name: 'COD_VALUTA', pos: 166, len: 4 },
        { name: 'DAT_INIZ_VAL', pos: 170, len: 10 },
        { name: 'COD_USER_INS', pos: 180, len: 8 },
        { name: 'TMS_INS', pos: 188, len: 28 },
        { name: 'COD_USER_MOD', pos: 214, len: 8 },
        { name: 'TMS_MOD', pos: 222, len: 28 }
    ],
    'DOC': [
        { name: 'COD_COMP', pos: 0, len: 4 },
        { name: 'TIP_DOCUMENTO', pos: 4, len: 2 },
        { name: 'NUM_DOCUMENTO', pos: 6, len: 14 },
        { name: 'NUM_CONTRATTO', pos: 20, len: 14 },
        { name: 'PRG_CONTRATTO', pos: 34, len: 8 },
        { name: 'COD_DOC_CLASSIF', pos: 42, len: 2 },
        { name: 'DAT_EFFETTO_COP', pos: 44, len: 10 },
        { name: 'DAT_SCAD_COP', pos: 54, len: 10 },
        { name: 'DAT_REGOLAZ', pos: 64, len: 10 },
        { name: 'TIP_DOCUMENTO_SOS', pos: 74, len: 2 },
        { name: 'NUM_DOCUMENTO_SOS', pos: 76, len: 14 },
        { name: 'NUM_AGENZIA_EMISS', pos: 90, len: 8 },
        { name: 'DAT_EMISSIONE', pos: 98, len: 10 },
        { name: 'COD_STATO', pos: 108, len: 1 },
        { name: 'COD_ANNULL_DOC', pos: 109, len: 1 },
        { name: 'NUM_DISTINTA', pos: 110, len: 14 },
        { name: 'NUM_OPERAZIONE', pos: 124, len: 6 },
        { name: 'NUM_QUESTION', pos: 130, len: 8 },
        { name: 'COD_SUB_CLASSIF', pos: 138, len: 1 },
        { name: 'DAT_CONVALIDA', pos: 139, len: 10 },
        { name: 'DAT_PAGAMENTO', pos: 149, len: 10 },
        { name: 'NUM_RIF_CATAL', pos: 159, len: 8 },
        { name: 'COD_CONVERS', pos: 167, len: 2 },
        { name: 'COD_VALUTA', pos: 169, len: 4 },
        { name: 'NUM_STAMPE', pos: 173, len: 4 },
        { name: 'COD_DIR_CONTI', pos: 177, len: 2 },
        { name: 'COD_FASE_CARTA', pos: 179, len: 1 },
        { name: 'COD_TRASM', pos: 180, len: 2 },
        { name: 'COD_ADEGUA', pos: 182, len: 1 },
        { name: 'COD_CONGUA', pos: 183, len: 1 },
        { name: 'COD_FIRMA', pos: 184, len: 1 },
        { name: 'NUM_VERSIONE', pos: 185, len: 6 },
        { name: 'PER_APP_BERS_PI', pos: 191, len: 6 },
        { name: 'PER_NUOVA_PROD_PA', pos: 197, len: 6 },
        { name: 'DAT_CONTAB_DOC', pos: 203, len: 10 },
        { name: 'COD_USER_INS', pos: 213, len: 8 },
        { name: 'TMS_INS', pos: 221, len: 26 },
        { name: 'COD_USER_MOD', pos: 247, len: 8 },
        { name: 'TMS_MOD', pos: 255, len: 28 },
        { name: 'COD_COMP_C', pos: 281, len: 4 },
        { name: 'TIP_CM', pos: 285, len: 3 },
        { name: 'FLG_DIGITALE', pos: 288, len: 1 },
        { name: 'FLG_RIEMISSIONE', pos: 289, len: 1 },
        { name: 'DAT_IMPOSTE', pos: 290, len: 10 },
        { name: 'TIP_OPERAZIONE', pos: 300, len: 3 },
        { name: 'COD_SUBPROCESSO', pos: 303, len: 3 },
        { name: 'COD_CONTABILITA', pos: 306, len: 1 },
        { name: 'COD_MOD_PAGAMENTO', pos: 307, len: 2 }
    ],
    'RIN': [
        { name: 'COD_COMP', pos: 0, len: 4 },
        { name: 'NUM_CONTRATTO', pos: 4, len: 14 },
        { name: 'PRG_CONTRATTO', pos: 18, len: 8 },
        { name: 'PRG_SCHEDA', pos: 26, len: 8 },
        { name: 'PRG_PARTITA', pos: 34, len: 6 },
        { name: 'KEY_OGG_RISCHIO', pos: 40, len: 12 },
        { name: 'COD_RUOLO', pos: 52, len: 3 },
        { name: 'NUM_QUESTION', pos: 55, len: 8 },
        { name: 'NUM_DOMANDA', pos: 63, len: 6 },
        { name: 'PRG_RISPOSTA', pos: 69, len: 4 },
        { name: 'NUM_RIGA_RISP', pos: 73, len: 4 },
        { name: 'DAT_FINE_VAL', pos: 77, len: 10 },
        { name: 'TIP_RISPOSTA', pos: 87, len: 1 },
        { name: 'TIP_DATA', pos: 88, len: 1 },
        { name: 'VAL_RISPOSTA', pos: 89, len: 14 },
        { name: 'TXT_RISPOSTA', pos: 103, len: 70 },
        { name: 'NUM_LISTA', pos: 173, len: 8 },
        { name: 'COD_VALUTA', pos: 181, len: 4 },
        { name: 'DAT_INIZ_VAL', pos: 185, len: 10 },
        { name: 'COD_USER_INS', pos: 195, len: 8 },
        { name: 'TMS_INS', pos: 203, len: 28 },
        { name: 'COD_USER_MOD', pos: 229, len: 8 },
        { name: 'TMS_MOD', pos: 237, len: 28 }
    ],
    'SFO': [
        { name: 'COD_COMP', pos: 0, len: 4 },
        { name: 'TIP_DOCUMENTO', pos: 4, len: 2 },
        { name: 'NUM_DOCUMENTO', pos: 6, len: 14 },
        { name: 'PRG_SFORATURA', pos: 20, len: 8 },
        { name: 'TIP_AUTOR', pos: 28, len: 3 },
        { name: 'KEY_REC_AUTOR', pos: 31, len: 24 },
        { name: 'COD_LIV_AUTOR', pos: 55, len: 2 },
        { name: 'COD_MOTIVO_AUTOR', pos: 57, len: 4 },
        { name: 'COD_STATO_SFO', pos: 61, len: 1 },
        { name: 'TXT_CATAL', pos: 62, len: 70 },
        { name: 'COD_USER_INS', pos: 132, len: 8 },
        { name: 'TMS_INS', pos: 140, len: 28 },
        { name: 'COD_USER_MOD', pos: 166, len: 8 },
        { name: 'TMS_MOD', pos: 174, len: 28 }
    ],
    'AGE': [
        { name: 'COD_COMP', pos: 0, len: 4 },
        { name: 'NUM_CONTRATTO', pos: 4, len: 14 },
        { name: 'PRG_CONTRATTO', pos: 18, len: 8 },
        { name: 'NUM_AGENZIA', pos: 26, len: 8 },
        { name: 'DAT_FINE_VAL', pos: 34, len: 10 },
        { name: 'COD_SUBAGENZIA', pos: 44, len: 5 },
        { name: 'COD_SUBAGENTE', pos: 49, len: 4 },
        { name: 'COD_PRODUTTORE', pos: 53, len: 7 },
        { name: 'COD_CARICO', pos: 60, len: 1 },
        { name: 'DAT_TRAS_SCOR', pos: 61, len: 10 },
        { name: 'DAT_EFF_COMPET', pos: 71, len: 10 },
        { name: 'DAT_REG_TRA_SCO', pos: 81, len: 10 },
        { name: 'NUM_AGENZIA_PREC', pos: 91, len: 8 },
        { name: 'DAT_SCAD_EFF_PREC', pos: 99, len: 10 },
        { name: 'PER_PROVV_ACQ', pos: 109, len: 6 },
        { name: 'PER_PROVV_INC', pos: 115, len: 6 },
        { name: 'DAT_CONTAB_GIRO', pos: 121, len: 10 },
        { name: 'DAT_INIZ_VAL', pos: 131, len: 10 },
        { name: 'COD_USER_INS', pos: 141, len: 8 },
        { name: 'TMS_INS', pos: 149, len: 28 },
        { name: 'COD_USER_MOD', pos: 175, len: 8 },
        { name: 'TMS_MOD', pos: 183, len: 28 },
        { name: 'COD_COMP_C', pos: 209, len: 4 },
        { name: 'COD_COMP_C_PREC', pos: 213, len: 4 }
    ],
    'COA': [
        { name: 'COD_COMP', pos: 0, len: 4 },
        { name: 'NUM_CONTRATTO', pos: 4, len: 14 },
        { name: 'PRG_CONTRATTO', pos: 18, len: 8 },
        { name: 'COD_DELEGATARIA', pos: 26, len: 1 },
        { name: 'COD_COMP_COASS', pos: 27, len: 4 },
        { name: 'NUM_AGENZIA_COASS', pos: 31, len: 8 },
        { name: 'DAT_FINE_VAL', pos: 39, len: 10 },
        { name: 'PER_QUOTA', pos: 49, len: 6 },
        { name: 'TXT_ULT_COMPAG', pos: 55, len: 70 },
        { name: 'COD_RIMBORSO', pos: 125, len: 2 },
        { name: 'DAT_INIZ_VAL', pos: 127, len: 10 },
        { name: 'COD_USER_INS', pos: 137, len: 8 },
        { name: 'TMS_INS', pos: 145, len: 28 },
        { name: 'COD_USER_MOD', pos: 171, len: 8 },
        { name: 'TMS_MOD', pos: 179, len: 28 },
        { name: 'PER_QUOTA_PREMIO', pos: 205, len: 6 },
        { name: 'FLG_DELEGA_SIN', pos: 211, len: 1 }
    ],
    'CVP': [
        { name: 'COD_COMP', pos: 0, len: 4 },
        { name: 'NUM_CONTRATTO', pos: 4, len: 14 },
        { name: 'PRG_CONTRATTO', pos: 18, len: 8 },
        { name: 'KEY_CONVENZIONE', pos: 26, len: 10 },
        { name: 'COD_CONVENZ_COMM', pos: 36, len: 6 },
        { name: 'DAT_INGRESSO_CONV', pos: 42, len: 10 },
        { name: 'DAT_USCITA_CONV', pos: 52, len: 10 },
        { name: 'COD_PROD_PARTIC', pos: 62, len: 1 },
        { name: 'COD_NAZIONALE', pos: 63, len: 1 },
        { name: 'COD_AZIENDA', pos: 64, len: 1 },
        { name: 'TIP_ACCORDO_CONV', pos: 65, len: 1 },
        { name: 'COD_USER_INS', pos: 66, len: 8 },
        { name: 'TMS_INS', pos: 74, len: 28 },
        { name: 'COD_USER_MOD', pos: 100, len: 8 },
        { name: 'TMS_MOD', pos: 108, len: 28 }
    ],
    'COI': [
        { name: 'COD_COMP', pos: 0, len: 4 },
        { name: 'NUM_CONTRATTO', pos: 4, len: 14 },
        { name: 'PRG_CONTRATTO', pos: 18, len: 8 },
        { name: 'COD_DATO', pos: 26, len: 10 },
        { name: 'COD_KEY_DATO', pos: 36, len: 30 },
        { name: 'DAT_FINE_VAL', pos: 66, len: 10 },
        { name: 'TIP_DATO', pos: 76, len: 3 },
        { name: 'TXT_DATO', pos: 79, len: 255 },
        { name: 'DAT_INIZ_VAL', pos: 334, len: 10 },
        { name: 'COD_USER_INS', pos: 344, len: 8 },
        { name: 'TMS_INS', pos: 352, len: 28 },
        { name: 'COD_USER_MOD', pos: 378, len: 8 },
        { name: 'TMS_MOD', pos: 386, len: 28 }
    ],
    'PCE': [
        { name: 'COD_COMP', pos: 0, len: 4 },
        { name: 'NUM_CONTRATTO', pos: 4, len: 14 },
        { name: 'PRG_CONTRATTO', pos: 18, len: 8 },
        { name: 'PRG_SCHEDA', pos: 26, len: 8 },
        { name: 'PRG_PARTITA', pos: 34, len: 8 },
        { name: 'PRG_RCD_PARAM', pos: 42, len: 2 },
        { name: 'NUM_PARAM', pos: 44, len: 3 },
        { name: 'DAT_RIFERIMENTO', pos: 47, len: 10 },
        { name: 'COD_COMUNICAZIONE', pos: 57, len: 1 },
        { name: 'DAT_FINE_VAL', pos: 58, len: 10 },
        { name: 'FLG_DECISIONALE', pos: 68, len: 4 },
        { name: 'FLG_AUMENTO_SCONTO', pos: 72, len: 1 },
        { name: 'DES_NOTA_LEN', pos: 73, len: 5 },
        { name: 'DES_NOTA_TEXT', pos: 78, len: 200 },
        { name: 'DES_PAR', pos: 278, len: 20 },
        { name: 'IMP_PAR', pos: 298, len: 16 },
        { name: 'COD_USER_INS', pos: 314, len: 8 },
        { name: 'TMS_INS', pos: 322, len: 28 },
        { name: 'COD_USER_MOD', pos: 348, len: 8 },
        { name: 'TMS_MOD', pos: 356, len: 28 },
        { name: 'DAT_INIZ_VAL', pos: 382, len: 10 },
        { name: 'PER_TASSO', pos: 392, len: 6 },
        { name: 'PER_INCRE', pos: 398, len: 6 },
        { name: 'IMP_PRE_MASSIMO', pos: 404, len: 14 }
    ],
    'LPS': [
        { name: 'COD_COMP', pos: 0, len: 4 },
        { name: 'NUM_CONTRATTO', pos: 4, len: 14 },
        { name: 'PRG_CONTRATTO', pos: 18, len: 8 },
        { name: 'PCT_NSQUOTA', pos: 26, len: 7 },
        { name: 'DATA_RIFERIMENTO', pos: 33, len: 10 },
        { name: 'PAESE', pos: 43, len: 3 },
        { name: 'DESCR_PAESE', pos: 46, len: 50 },
        { name: 'VAL_ASSIC', pos: 96, len: 14 },
        { name: 'VAL_ASSIC_DI', pos: 110, len: 14 },
        { name: 'TAB_PARAM', pos: 124, len: 60 },
        { name: 'TAB_GAR', pos: 184, len: 567 }
    ],
    'PCB': [
        { name: 'COD_COMP', pos: 0, len: 4 },
        { name: 'NUM_CONTRATTO', pos: 4, len: 14 },
        { name: 'PRG_CONTRATTO', pos: 18, len: 8 },
        { name: 'PRG_SCHEDA', pos: 26, len: 8 },
        { name: 'PRG_PARTITA', pos: 34, len: 6 },
        { name: 'PRG_RECORD', pos: 40, len: 4 },
        { name: 'DAT_FINE_VAL', pos: 44, len: 10 },
        { name: 'PER_RIPART', pos: 54, len: 8 },
        { name: 'COD_RAMO_FORTE', pos: 62, len: 5 },
        { name: 'DAT_INIZ_VAL', pos: 67, len: 10 },
        { name: 'COD_USER_INS', pos: 77, len: 8 },
        { name: 'TMS_INS', pos: 85, len: 28 },
        { name: 'COD_USER_MOD', pos: 111, len: 8 },
        { name: 'TMS_MOD', pos: 119, len: 28 }
    ],

    // ===== BLOCCHI ENTITÀ ANAGRAFICHE =====
    'CPERSONA': [
        { name: 'COD_TIPO_EA', pos: 0, len: 2 },
        { name: 'COD_KEY_EA', pos: 3, len: 11 },
        { name: 'COD_TITOLO', pos: 15, len: 5 },
        { name: 'TXT_COGNOME', pos: 20, len: 35 },
        { name: 'TXT_COGNOME2', pos: 55, len: 35 },
        { name: 'TXT_NOME', pos: 90, len: 35 },
        { name: 'COD_SESSO', pos: 125, len: 1 },
        { name: 'DAT_NASCITA', pos: 126, len: 10 },
        { name: 'COD_NAZIONALI', pos: 136, len: 3 },
        { name: 'TXT_COMU_NASC', pos: 139, len: 40 },
        { name: 'COD_PROV_NASC', pos: 179, len: 3 },
        { name: 'COD_NAZI_NASC', pos: 182, len: 3 },
        { name: 'COD_FISCALE', pos: 185, len: 16 },
        { name: 'COD_STAT_CIVL', pos: 201, len: 2 },
        { name: 'COD_UNIT_MERC', pos: 204, len: 4 },
        { name: 'COD_PROFESSIO', pos: 209, len: 6 },
        { name: 'COD_SOTT_GRUP', pos: 216, len: 3 },
        { name: 'COD_GRUP_ATCO', pos: 220, len: 3 },
        { name: 'COD_TIPO_PERS', pos: 224, len: 1 },
        { name: 'NUM_MATRICOLA', pos: 225, len: 15 },
        { name: 'DAT_MORTE', pos: 240, len: 10 },
        { name: 'COD_MOTI_MORT', pos: 250, len: 4 },
        { name: 'COD_IMPERDIBI', pos: 255, len: 1 },
        { name: 'FLG_FORZ_CFIS', pos: 256, len: 1 },
        { name: 'DAT_INIZ_VALI', pos: 257, len: 10 },
        { name: 'ORA_INIZ_VALI', pos: 267, len: 8 },
        { name: 'DAT_INSERT', pos: 275, len: 26 },
        { name: 'COD_USER', pos: 301, len: 8 },
        { name: 'DAT_FINE_VALI', pos: 309, len: 10 }
    ],
    'CNATANTE': [
        { name: 'COD_TIPO_EA', pos: 0, len: 2 },
        { name: 'COD_KEY_EA', pos: 3, len: 11 },
        { name: 'MATR', pos: 15, len: 20 },
        { name: 'CHIAVE', pos: 35, len: 1 },
        { name: 'DEST_USO', pos: 37, len: 6 },
        { name: 'MODELLO', pos: 44, len: 70 },
        { name: 'NOME', pos: 114, len: 20 },
        { name: 'SIGL_COST', pos: 134, len: 20 },
        { name: 'BANDIERA', pos: 154, len: 15 },
        { name: 'NATANTE', pos: 169, len: 1 },
        { name: 'TIPO_USO', pos: 171, len: 1 },
        { name: 'BAND_LPS', pos: 173, len: 3 },
        { name: 'NAZIONE', pos: 176, len: 6 },
        { name: 'PERIZIA', pos: 183, len: 1 },
        { name: 'MOTORI', pos: 185, len: 2 },
        { name: 'ANNO_COST', pos: 188, len: 4 },
        { name: 'MESE_COST', pos: 193, len: 2 },
        { name: 'STAZ_LORD', pos: 196, len: 6 },
        { name: 'LUNGHEZZA', pos: 205, len: 3 },
        { name: 'POSTI', pos: 211, len: 4 },
        { name: 'NODI_VELO', pos: 216, len: 3 },
        { name: 'MATE_COST', pos: 220, len: 2 },
        { name: 'SPEC_ALBE', pos: 223, len: 1 },
        { name: 'SATELLITARE', pos: 225, len: 2 },
        { name: 'COLORE', pos: 228, len: 2 },
        { name: 'LARGHEZZA', pos: 231, len: 3 },
        { name: 'PESCAGGIO', pos: 237, len: 3 },
        { name: 'VELO_CROC', pos: 243, len: 3 },
        { name: 'ARMAMENTO', pos: 247, len: 2 },
        { name: 'CONSUMO', pos: 250, len: 3 },
        { name: 'LITR_SERB', pos: 256, len: 5 },
        { name: 'ELETTRONICA', pos: 262, len: 2 },
        { name: 'SAT1', pos: 265, len: 15 },
        { name: 'SAT2', pos: 280, len: 15 },
        { name: 'SAT3', pos: 295, len: 15 },
        { name: 'GSM1', pos: 310, len: 15 },
        { name: 'GSM2', pos: 325, len: 15 },
        { name: 'GSM3', pos: 340, len: 15 },
        { name: 'INDI_USO', pos: 355, len: 1 },
        { name: 'PORTO', pos: 357, len: 6 },
        { name: 'CAT_PORT', pos: 364, len: 3 },
        { name: 'RIFE_PORT', pos: 368, len: 6 },
        { name: 'SETTORE', pos: 375, len: 1 },
        { name: 'CLASSE', pos: 376, len: 2 },
        { name: 'USO', pos: 378, len: 2 },
        { name: 'DAT_INIZ_VALI', pos: 380, len: 10 },
        { name: 'ORA_INIZ_VALI', pos: 390, len: 10 },
        { name: 'TMS_INSERT', pos: 400, len: 26 },
        { name: 'COD_USER', pos: 426, len: 8 },
        { name: 'DAT_FINE_VALI', pos: 434, len: 10 }
    ],
    'CIMPRESA': [
        { name: 'COD_TIPO_EA', pos: 0, len: 2 },
        { name: 'COD_KEY_EA', pos: 3, len: 11 },
        { name: 'COD_RAGI_SOCI', pos: 15, len: 6 },
        { name: 'TXT_RAGI_SOCI', pos: 22, len: 40 },
        { name: 'TXT_RAGI_SOCI2', pos: 62, len: 40 },
        { name: 'COD_FORM_SOCI', pos: 102, len: 6 },
        { name: 'DAT_FONDAZIONE', pos: 109, len: 10 },
        { name: 'COD_FISCALE', pos: 119, len: 16 },
        { name: 'COD_NAZI_PIVA', pos: 135, len: 2 },
        { name: 'COD_PART_IVA', pos: 137, len: 12 },
        { name: 'COD_UNIT_MERC', pos: 149, len: 4 },
        { name: 'COD_SETT_ATTI', pos: 154, len: 6 },
        { name: 'COD_SOTT_GRUP_ATCO', pos: 161, len: 3 },
        { name: 'COD_GRUP_ATCO', pos: 165, len: 3 },
        { name: 'DAT_SCIOGLIMENTO', pos: 169, len: 10 },
        { name: 'COD_FASC_FATT', pos: 179, len: 2 },
        { name: 'COD_IMPERDIBILE', pos: 182, len: 1 },
        { name: 'FLG_FORZ_CFIS', pos: 183, len: 1 },
        { name: 'COD_NUM_DIPE', pos: 184, len: 2 },
        { name: 'FLG_ENTE_PUBB', pos: 187, len: 1 },
        { name: 'ORA_INIZ_VALI', pos: 188, len: 8 },
        { name: 'DAT_INSERT', pos: 196, len: 26 },
        { name: 'COD_USER', pos: 222, len: 8 },
        { name: 'DAT_FINE_VALI', pos: 230, len: 10 },
        { name: 'PERSONA_RIF', pos: 240, len: 40 },
        { name: 'TIPO_ENTE', pos: 280, len: 1 },
        { name: 'FORZATURA', pos: 281, len: 1 },
        { name: 'FATTURATO', pos: 282, len: 15 },
        { name: 'NAZIONALITA', pos: 298, len: 3 },
        { name: 'DAT_INIZ_VALI', pos: 301, len: 10 }
    ],
    'CFABBRICATO': [
        { name: 'COD_TIPO_EA', pos: 0, len: 2 },
        { name: 'COD_KEY_EA', pos: 3, len: 11 },
        { name: 'COD_CATALOGO', pos: 15, len: 3 },
        { name: 'COD_DEST_USO', pos: 19, len: 6 },
        { name: 'NUM_ANNO_EDIF', pos: 26, len: 4 },
        { name: 'NUM_PIANI', pos: 31, len: 3 },
        { name: 'DAT_INIZ_VALI', pos: 35, len: 10 },
        { name: 'ORA_INIZ_VALI', pos: 45, len: 8 },
        { name: 'DAT_INSERT', pos: 53, len: 26 },
        { name: 'COD_USER', pos: 79, len: 8 },
        { name: 'DAT_FINE_VALI', pos: 88, len: 10 }
    ],
    'CUBICAZIONE': [
        { name: 'COD_TIPO_EA', pos: 0, len: 2 },
        { name: 'COD_KEY_EA', pos: 3, len: 11 },
        { name: 'COD_PREF_TOP', pos: 15, len: 6 },
        { name: 'TXT_PREF_BREV', pos: 22, len: 10 },
        { name: 'TXT_INDIRIZZO', pos: 32, len: 35 },
        { name: 'NUM_CIVICO', pos: 67, len: 15 },
        { name: 'NUM_SCALA', pos: 82, len: 1 },
        { name: 'TXT_COMUNE', pos: 83, len: 40 },
        { name: 'COD_PROVINCIA', pos: 123, len: 3 },
        { name: 'COD_CAP', pos: 126, len: 9 },
        { name: 'COD_TERRITORIO', pos: 135, len: 6 },
        { name: 'TXT_LOCALITA', pos: 142, len: 40 },
        { name: 'COD_LOCALITA', pos: 182, len: 6 },
        { name: 'COD_NAZIONE', pos: 189, len: 3 },
        { name: 'TXT_TOPONIMO', pos: 192, len: 35 },
        { name: 'DAT_INIZ_VALI', pos: 227, len: 10 },
        { name: 'ORA_INIZ_VALI', pos: 237, len: 8 },
        { name: 'DAT_INSERT', pos: 245, len: 26 },
        { name: 'COD_USER', pos: 271, len: 8 },
        { name: 'DAT_FINE_VALI', pos: 279, len: 10 },
        { name: 'COD_PROV_MCZ', pos: 289, len: 3 },
        { name: 'COD_COMUNE_MCZ', pos: 293, len: 3 },
        { name: 'COD_SEZIONE_MCZI', pos: 297, len: 7 }
    ],
    'CATTIVITA': [
        { name: 'COD_TIPO_EA', pos: 0, len: 2 },
        { name: 'COD_KEY_EA', pos: 3, len: 11 },
        { name: 'COD_ATTIVITA', pos: 15, len: 2 },
        { name: 'COD_CATALOGO', pos: 18, len: 3 },
        { name: 'NUM_RIFE_ATTI', pos: 22, len: 6 },
        { name: 'COD_CONTINUITA', pos: 29, len: 1 },
        { name: 'NUM_MESI_ATTI', pos: 30, len: 2 },
        { name: 'NUM_PERSONE', pos: 33, len: 5 },
        { name: 'COD_PESO', pos: 39, len: 1 },
        { name: 'PRC_PESO', pos: 40, len: 5 },
        { name: 'DAT_INIZ_VALI', pos: 46, len: 10 },
        { name: 'ORA_INIZ_VALI', pos: 56, len: 8 },
        { name: 'DAT_INSERT', pos: 64, len: 26 },
        { name: 'COD_USER', pos: 90, len: 8 },
        { name: 'DAT_FINE_VALI', pos: 98, len: 10 }
    ],
    'CVEICOLO': [
        { name: 'COD_KEY_EA', pos: 3, len: 11 },
        { name: 'TXT_TARGA_TELA', pos: 19, len: 20 },
        { name: 'COD_TIPO_VEIC', pos: 68, len: 6 },
        { name: 'COD_MARCA', pos: 79, len: 6 },
        { name: 'COD_MODELLO', pos: 86, len: 6 },
        { name: 'COD_VERSIONE', pos: 93, len: 6 },
        { name: 'DAT_IMMATRICOLAZIO', pos: 249, len: 15 }
    ],
    'CENTITASTRINGA': [
        { name: 'COD_KEY_EA', pos: 3, len: 11 },
        { name: 'TXT_STRINGA', pos: 15, len: 255 }
    ],
    'CGRUPPOANAG': [
        { name: 'COD_TIPO_EA', pos: 0, len: 2 },
        { name: 'COD_KEY_EA', pos: 3, len: 11 },
        { name: 'TXT_GRUPPO', pos: 15, len: 50 },
        { name: 'COD_GRUPPO', pos: 65, len: 7 },
        { name: 'TIPO_GRUPPO', pos: 73, len: 2 }
    ],
    'CAEROMOBILE': [
        { name: 'COD_TIPO_EA', pos: 0, len: 2 },
        { name: 'COD_KEY_EA', pos: 3, len: 11 },
        { name: 'COD_TIPOL', pos: 15, len: 11 },
        { name: 'COD_IDTARGA', pos: 27, len: 8 },
        { name: 'COD_NAZIONE', pos: 35, len: 3 },
        { name: 'TXT_MARCA', pos: 38, len: 40 },
        { name: 'TXT_MODELLO', pos: 78, len: 40 },
        { name: 'VAL_PESO', pos: 118, len: 7 },
        { name: 'POSTI_PIL', pos: 126, len: 3 },
        { name: 'POSTI_TEC', pos: 130, len: 3 },
        { name: 'POSTI_PAS', pos: 134, len: 3 },
        { name: 'NUM_ANNO_COST', pos: 138, len: 4 },
        { name: 'NUM_COSTRUZ', pos: 143, len: 12 },
        { name: 'COD_USO', pos: 155, len: 6 },
        { name: 'INIZ_VALI', pos: 162, len: 10 },
        { name: 'ORA_INIZ_VALI', pos: 172, len: 8 },
        { name: 'DAT_INSERT', pos: 180, len: 26 },
        { name: 'COD_USER', pos: 206, len: 8 },
        { name: 'DAT_FINE_VALI', pos: 214, len: 10 }
    ],
    'CUSISPECIALI': [
        { name: 'COD_TIPO_EA', pos: 0, len: 2 },
        { name: 'COD_KEY_EA', pos: 3, len: 11 },
        { name: 'PRG_USO', pos: 15, len: 2 },
        { name: 'COD_CATALOGO', pos: 18, len: 6 },
        { name: 'ORA_INIZ_VALI', pos: 25, len: 8 },
        { name: 'DAT_INSERT', pos: 33, len: 26 },
        { name: 'COD_USER', pos: 59, len: 8 },
        { name: 'DAT_FINE_VALI', pos: 67, len: 10 },
        { name: 'TXT_DES_ALTRO', pos: 77, len: 204 }
    ],
    'CANIMALE': [
        { name: 'COD_TIPO_EA', pos: 0, len: 2 },
        { name: 'COD_KEY_EA', pos: 3, len: 11 },
        { name: 'TXT_NOME', pos: 15, len: 60 },
        { name: 'COD_SPECIE', pos: 75, len: 6 },
        { name: 'COD_RAZZA', pos: 82, len: 6 },
        { name: 'COD_MICROCHIP', pos: 89, len: 15 },
        { name: 'DAT_NASCITA', pos: 104, len: 10 },
        { name: 'COD_SESSO', pos: 114, len: 1 },
        { name: 'DAT_INIZ_VALI', pos: 115, len: 10 },
        { name: 'ORA_INIZ_VALI', pos: 125, len: 8 },
        { name: 'DAT_INSERT', pos: 133, len: 26 },
        { name: 'COD_USER', pos: 159, len: 8 },
        { name: 'DAT_FINE_VALI', pos: 167, len: 10 }
    ],

    // ===== BLOCCHI RELAZIONI =====
    'CRELAZIONERR': [
        { name: 'COD_KEY_EASX', pos: 0, len: 11 },
        { name: 'COD_KEY_EADX', pos: 12, len: 11 },
        { name: 'COD_RUOL', pos: 24, len: 2 },
        { name: 'DAT_INIZ_VALI', pos: 26, len: 10 },
        { name: 'ORA_INIZ_VALI', pos: 36, len: 8 }
    ],
    'CRELAZIONEGR': [
        { name: 'COD_KEY_EASX', pos: 0, len: 11 },
        { name: 'COD_KEY_EADX', pos: 12, len: 11 },
        { name: 'COD_TIPL_LEGA', pos: 24, len: 2 },
        { name: 'COD_LEGAME', pos: 27, len: 2 },
        { name: 'DAT_INIZ_VALI', pos: 28, len: 10 },
        { name: 'ORA_INIZ_VALI', pos: 38, len: 8 }
    ],
    'CRELAZIONECR': [
        { name: 'COD_COMP', pos: 0, len: 4 },
        { name: 'NUM_CONTRATTO', pos: 4, len: 14 },
        { name: 'PRG_CONTRATTO', pos: 18, len: 8 },
        { name: 'PRG_SCHEDA', pos: 26, len: 8 },
        { name: 'PRG_PARTITA', pos: 34, len: 6 },
        { name: 'TIP_PORTAF', pos: 40, len: 3 },
        { name: 'COD_TIPO_EA', pos: 43, len: 3 },
        { name: 'KEY_OGG_RISCHIO', pos: 46, len: 12 },
        { name: 'COD_RUOLO', pos: 58, len: 3 },
        { name: 'DAT_INIZ_VALI', pos: 61, len: 10 },
        { name: 'DAT_FINE_VALI', pos: 71, len: 10 }
    ],

    // ===== BLOCCHI VARIANTI (non supportati, array vuoti) =====
    'CPERSGRUP': [],
    'CPERSAERO': [],
    'CUBICAZGRUP': [],
    'CUBICAZAERO': [],
    'CIMPRESAGRUP': [],
    'CRELAZRRAERO': [],
    'CRELAZRRGRUP': []
};
